### ISSUE TITLE
When setup run.sh, is there anyone facing this problom: CUDA error: invalid device function，

### ISSUE THREAD

**Issue by isekeylabSunQixiang** [kchengiva/Shift-GCN#14]
Environment: PyTorch 1.4, Cuda 10.0, Python1.7,cudnn7.6.4.
Already finished processing dependencies
`shift-cuda-linear-cpp 0.0.0 is already the active version in easy-install.pth

Installed /root/anaconda3/lib/python3.7/site-packages/shift_cuda_linear_cpp-0.0.0-py3.7-linux-x86_64.egg
Processing dependencies for shift-cuda-linear-cpp==0.0.0
Finished processing dependencies for shift-cuda-linear-cpp==0.0.0
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    sum_out = torch.sum(out)
RuntimeError: CUDA error: invalid device function
`
I googled, and it seems that there is a mismatch between the compute capability of your GPU device and the compute capabilities for Shift-GCN, then I try to find a make file to modify compute capability, but I failed. Is there any solution to this problem?

Appreciate

**Comment by isekeylabSunQixiang** [comment]
I changed a new server, using a new environment: Cuda 10.2, PyTorch1.5, Python3.6. problem solved
Appreciate your fantastic work
